development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: reu_development
  pool: 5
  username: root
  password: Wertyos888

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: reu_test
  pool: 5
  username: root
  password: Wertyos888

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: reu_prod
  pool: 5
  username: root
  password: Wertyos888
